### PR TITLE
Unhandled exceptions fix

### PR DESCRIPTION
**Pull request by LeeSaferite**

### CODE REVIEW

**Comment by LeeSaferite** [comment]
See #3

**Comment by LeeSaferite** [comment]
I suggest looking at this PR with the w=1 query param since I unified the line-endings of the whole module before I made changes.

**Comment by LeeSaferite** [comment]
@fbrnc Can you please review this PR?

**Comment by sourcesoldier** [comment]
The changes have been merged into this branch https://github.com/AOEpeople/Aoe_Queue/tree/exception_retry

**Pull request closed without merging**
